In [2]:
import fastf1
import pandas as pd
from datetime import datetime

In [3]:
now = datetime.now()

df_calendar = pd.DataFrame()

actual_year = now.year
actual_date = pd.to_datetime(now.strftime("%Y-%m-%d"))

In [9]:
def get_calendar(year):
    calendar = fastf1.get_event_schedule(year)
    
    df_calendar = calendar.copy()

    colonnes = [
        'RoundNumber','Country','Location','EventDate','EventName',
        'Session1','Session1DateUtc','Session2','Session2DateUtc',
        'Session3','Session3DateUtc','Session4','Session4DateUtc',
        'Session5','Session5DateUtc'
    ]
    
    df_calendar = df_calendar[colonnes]

    sessions_cols = ['Session1DateUtc', 'Session2DateUtc', 'Session3DateUtc','Session4DateUtc', 'Session5DateUtc']
    
    df_calendar['EventDate'] = pd.to_datetime(df_calendar['EventDate'])
    
    for col in sessions_cols:
        df_calendar[col] = (pd.to_datetime(df_calendar[col], utc=True).dt.tz_convert("Europe/Paris"))

    return df_calendar

df_calendar = get_calendar(2026)
df_calendar

,RoundNumber,Country,Location,EventDate,EventName,Session1,Session1DateUtc,Session2,Session2DateUtc,Session3,Session3DateUtc,Session4,Session4DateUtc,Session5,Session5DateUtc
0,0,Bahrain,Bahrain,2026-02-13,Pre-Season Testing,Practice 1,2026-02-11 08:00:00+01:00,Practice 2,2026-02-12 08:00:00+01:00,Practice 3,2026-02-13 08:00:00+01:00,None,NaT,None,NaT
1,0,Bahrain,Bahrain,2026-02-20,Pre-Season Testing,Practice 1,2026-02-18 08:00:00+01:00,Practice 2,2026-02-19 08:00:00+01:00,Practice 3,2026-02-20 08:00:00+01:00,None,NaT,None,NaT
2,1,Australia,Melbourne,2026-03-08,Australian Grand Prix,Practice 1,2026-03-06 02:30:00+01:00,Practice 2,2026-03-06 06:00:00+01:00,Practice 3,2026-03-07 02:30:00+01:00,Qualifying,2026-03-07 06:00:00+01:00,Race,2026-03-08 05:00:00+01:00
3,2,China,Shanghai,2026-03-15,Chinese Grand Prix,Practice 1,2026-03-13 04:30:00+01:00,Sprint Qualifying,2026-03-13 08:30:00+01:00,Sprint,2026-03-14 04:00:00+01:00,Qualifying,2026-03-14 08:00:00+01:00,Race,2026-03-15 08:00:00+01:00
4,3,Japan,Suzuka,2026-03-29,Japanese Grand Prix,Practice 1,2026-03-27 03:30:00+01:00,Practice 2,2026-03-27 07:00:00+01:00,Practice 3,2026-03-28 03:30:00+01:00,Qualifying,2026-03-28 07:00:00+01:00,Race,2026-03-29 07:00:00+02:00
5,4,Bahrain,Sakhir,2026-04-12,Bahrain Grand Prix,Practice 1,2026-04-10 13:30:00+02:00,Practice 2,2026-04-10 17:00:00+02:00,Practice 3,2026-04-11 14:30:00+02:00,Qualifying,2026-04-11 18:00:00+02:00,Race,2026-04-12 17:00:00+02:00
6,5,Saudi Arabia,Jeddah,2026-04-19,Saudi Arabian Grand Prix,Practice 1,2026-04-17 15:30:00+02:00,Practice 2,2026-04-17 19:00:00+02:00,Practice 3,2026-04-18 15:30:00+02:00,Qualifying,2026-04-18 19:00:00+02:00,Race,2026-04-19 19:00:00+02:00
7,6,United States,Miami Gardens,2026-05-03,Miami Grand Prix,Practice 1,2026-05-01 18:30:00+02:00,Sprint Qualifying,2026-05-01 22:30:00+02:00,Sprint,2026-05-02 18:00:00+02:00,Qualifying,2026-05-02 22:00:00+02:00,Race,2026-05-03 22:00:00+02:00
8,7,Canada,Montréal,2026-05-24,Canadian Grand Prix,Practice 1,2026-05-22 18:30:00+02:00,Sprint Qualifying,2026-05-22 22:30:00+02:00,Sprint,2026-05-23 18:00:00+02:00,Qualifying,2026-05-23 22:00:00+02:00,Race,2026-05-24 22:00:00+02:00
9,8,Monaco,Monte Carlo,2026-06-07,Monaco Grand Prix,Practice 1,2026-06-05 13:30:00+02:00,Practice 2,2026-06-05 17:00:00+02:00,Practice 3,2026-06-06 12:30:00+02:00,Qualifying,2026-06-06 16:00:00+02:00,Race,2026-06-07 15:00:00+02:00
10,9,Spain,Barcelona,2026-06-14,Barcelona Grand Prix,Practice 1,2026-06-12 13:30:00+02:00,Practice 2,2026-06-12 17:00:00+02:00,Practice 3,2026-06-13 12:30:00+02:00,Qualifying,2026-06-13 16:00:00+02:00,Race,2026-06-14 15:00:00+02:00
11,10,Austria,Spielberg,2026-06-28,Austrian Grand Prix,Practice 1,2026-06-26 13:30:00+02:00,Practice 2,2026-06-26 17:00:00+02:00,Practice 3,2026-06-27 12:30:00+02:00,Qualifying,2026-06-27 16:00:00+02:00,Race,2026-06-28 15:00:00+02:00
12,11,United Kingdom,Silverstone,2026-07-05,British Grand Prix,Practice 1,2026-07-03 13:30:00+02:00,Sprint Qualifying,2026-07-03 17:30:00+02:00,Sprint,2026-07-04 13:00:00+02:00,Qualifying,2026-07-04 17:00:00+02:00,Race,2026-07-05 16:00:00+02:00
13,12,Belgium,Spa-Francorchamps,2026-07-19,Belgian Grand Prix,Practice 1,2026-07-17 13:30:00+02:00,Practice 2,2026-07-17 17:00:00+02:00,Practice 3,2026-07-18 12:30:00+02:00,Qualifying,2026-07-18 16:00:00+02:00,Race,2026-07-19 15:00:00+02:00
14,13,Hungary,Budapest,2026-07-26,Hungarian Grand Prix,Practice 1,2026-07-24 13:30:00+02:00,Practice 2,2026-07-24 17:00:00+02:00,Practice 3,2026-07-25 12:30:00+02:00,Qualifying,2026-07-25 16:00:00+02:00,Race,2026-07-26 15:00:00+02:00
15,14,Netherlands,Zandvoort,2026-08-23,Dutch Grand Prix,Practice 1,2026-08-21 12:30:00+02:00,Sprint Qualifying,2026-08-21 16:30:00+02:00,Sprint,2026-08-22 12:00:00+02:00,Qualifying,2026-08-22 16:00:00+02:00,Race,2026-08-23 15:00:00+02:00
16,15,Italy,Monza,2026-09-06,Italian Grand Prix,Practice 1,2026-09-04 12:30:00+02:00,Practice 2,2026-09-04 16:00:00+02:00,Practice 3,2026-09-05 12:30:00+02:00,Qualifying,2026-09-05 16:00:00+02:00,Race,2026-09-06 15:00:00+02:00
17,16,Spain,Madrid,2026-09-13,Spanish Grand Prix,Practice 1,2026-09-11 13:30:00+02:00,Practice 2,2026-09-11 17:00:00+02:00,Practice 3,2026-09-12 12:30:00+02:00,Qualifying,2026-09-12 16:00:00+02:00,Race,2026-09-13 15:00:00+02:00
18,17,Azerbaijan,Baku,2026-09-26,Azerbaijan Grand Prix,Practice 1,2026-09-24 10:30:00+02:00,Practice 2,2026-09-24 14:00:00+02:00,Practice 3,2026-09-25 10:30:00+02:00,Qualifying,2026-09-25 14:00:00+02:00,Race,2026-09-26 13:00:00+02:00
19,18,Singapore,Marina Bay,2026-10-11,Singapore Grand Prix,Practice 1,2026-10-09 10:30:00+02:00,Sprint Qualifying,2026-10-09 14:30:00+02:00,Sprint,2026-10-10 11:00:00+02:00,Qualifying,2026-10-10 15:00:00+02:00,Race,2026-10-11 14:00:00+02:00
20,19,United States,Austin,2026-10-25,United States Grand Prix,Practice 1,2026-10-23 19:30:00+02:00,Practice 2,2026-10-23 23:00:00+02:00,Practice 3,2026-10-24 19:30:00+02:00,Qualifying,2026-10-24 23:00:00+02:00,Race,2026-10-25 21:00:00+01:00
21,20,Mexico,Mexico City,2026-11-01,Mexico City Grand Prix,Practice 1,2026-10-30 19:30:00+01:00,Practice 2,2026-10-30 23:00:00+01:00,Practice 3,2026-10-31 18:30:00+01:00,Qualifying,2026-10-31 22:00:00+01:00,Race,2026-11-01 21:00:00+01:00
22,21,Brazil,São Paulo,2026-11-08,São Paulo Grand Prix,Practice 1,2026-11-06 16:30:00+01:00,Practice 2,2026-11-06 20:00:00+01:00,Practice 3,2026-11-07 15:30:00+01:00,Qualifying,2026-11-07 19:00:00+01:00,Race,2026-11-08 18:00:00+01:00
23,22,United States,Las Vegas,2026-11-21,Las Vegas Grand Prix,Practice 1,2026-11-20 01:30:00+01:00,Practice 2,2026-11-20 05:00:00+01:00,Practice 3,2026-11-21 01:30:00+01:00,Qualifying,2026-11-21 05:00:00+01:00,Race,2026-11-22 05:00:00+01:00
24,23,Qatar,Lusail,2026-11-29,Qatar Grand Prix,Practice 1,2026-11-27 14:30:00+01:00,Practice 2,2026-11-27 18:00:00+01:00,Practice 3,2026-11-28 15:30:00+01:00,Qualifying,2026-11-28 19:00:00+01:00,Race,2026-11-29 17:00:00+01:00
25,24,United Arab Emirates,Yas Marina,2026-12-06,Abu Dhabi Grand Prix,Practice 1,2026-12-04 10:30:00+01:00,Practice 2,2026-12-04 14:00:00+01:00,Practice 3,2026-12-05 11:30:00+01:00,Qualifying,2026-12-05 15:00:00+01:00,Race,2026-12-06 14:00:00+01:00

In [17]:
s_sess = fastf1.get_session(2026, 1, 'R')
s_sess.load(telemetry=False, weather=False, messages=False)

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

In [30]:
s_sess.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,6.0,6,20.0,NaT,NaT,NaT,0 days 00:00:54.617000,Finished,8.0,58.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,7.0,7,12.0,NaT,NaT,NaT,0 days 00:00:04.593000,Lapped,6.0,57.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,8.0,8,9.0,NaT,NaT,NaT,0 days 00:00:11.816000,Lapped,4.0,57.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,9.0,9,10.0,NaT,NaT,NaT,0 days 00:00:12.775000,Lapped,2.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,10.0,10,14.0,NaT,NaT,NaT,0 days 00:00:29.027000,Lapped,1.0,57.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,11.0,11,13.0,NaT,NaT,NaT,0 days 00:00:29.850000,Lapped,0.0,57.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,12.0,12,15.0,NaT,NaT,NaT,0 days 00:00:56.075000,Lapped,0.0,57.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,13.0,13,8.0,NaT,NaT,NaT,0 days 00:00:57.173000,Lapped,0.0,57.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,14,16.0,NaT,NaT,NaT,0 days 00:00:08.487000,Lapped,0.0,56.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,15.0,15,21.0,NaT,NaT,NaT,0 days 00:00:36.886000,Lapped,0.0,56.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,16.0,16,18.0,NaT,NaT,NaT,0 days 00:00:07.850000,Lapped,0.0,55.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,17.0,R,22.0,NaT,NaT,NaT,NaT,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,18.0,R,17.0,NaT,NaT,NaT,NaT,Retired,0.0,21.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,19.0,R,19.0,NaT,NaT,NaT,NaT,Retired,0.0,15.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,20.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,10.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,21.0,W,5.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,22.0,W,11.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0

In [19]:
s_sess.drivers

['63',
 '12',
 '16',
 '44',
 '1',
 '3',
 '87',
 '41',
 '5',
 '10',
 '31',
 '23',
 '30',
 '43',
 '55',
 '11',
 '18',
 '14',
 '77',
 '6',
 '81',
 '27']

In [28]:
s_sess.laps.pick_driver('PIA')

c:\Users\mike5\anaconda3\Lib\site-packages\fastf1\core.py:3129: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.
  warnings.warn(("pick_driver is deprecated and will be removed"

Empty DataFrame
Columns: [Time, Driver, DriverNumber, LapTime, LapNumber, Stint, PitOutTime, PitInTime, Sector1Time, Sector2Time, Sector3Time, Sector1SessionTime, Sector2SessionTime, Sector3SessionTime, SpeedI1, SpeedI2, SpeedFL, SpeedST, IsPersonalBest, Compound, TyreLife, FreshTyre, Team, LapStartTime, LapStartDate, TrackStatus, Position, Deleted, DeletedReason, FastF1Generated, IsAccurate]
Index: []

[0 rows x 31 columns]

In [27]:
s_sess.get_driver('PIA')

DriverNumber                                                         81
BroadcastName                                                 O PIASTRI
Abbreviation                                                        PIA
DriverId                                                        piastri
TeamName                                                        McLaren
TeamColor                                                        F47600
TeamId                                                          mclaren
FirstName                                                         Oscar
LastName                                                        Piastri
FullName                                                  Oscar Piastri
HeadshotUrl           https://media.formula1.com/d_driver_fallback_i...
CountryCode
Position                                                           21.0
ClassifiedPosition                                                    W
GridPosition                                                        5.0
Q1                                                                  NaT
Q2                                                                  NaT
Q3                                                                  NaT
Time                                                                NaT
Status                                                    Did not start
Points                                                              0.0
Laps                                                                0.0
Name: 81, dtype: object