In [1]:
import fastf1
import pandas as pd
from datetime import datetime

In [3]:
now = datetime.now()

df_calendar = pd.DataFrame()

actual_year = now.year
actual_date = pd.to_datetime(now.strftime("%Y-%m-%d"))

In [4]:
def get_calendar(year):
    calendar = fastf1.get_event_schedule(year)
    
    df_calendar = calendar.copy()

    colonnes = [
        'RoundNumber','Country','Location','EventDate','EventName',
        'Session1','Session1DateUtc','Session2','Session2DateUtc',
        'Session3','Session3DateUtc','Session4','Session4DateUtc',
        'Session5','Session5DateUtc'
    ]
    
    df_calendar = df_calendar[colonnes]

    sessions_cols = ['Session1DateUtc', 'Session2DateUtc', 'Session3DateUtc','Session4DateUtc', 'Session5DateUtc']
    
    df_calendar['EventDate'] = pd.to_datetime(df_calendar['EventDate'])
    
    for col in sessions_cols:
        df_calendar[col] = (pd.to_datetime(df_calendar[col], utc=True).dt.tz_convert("Europe/Paris"))

    return df_calendar

df_calendar = get_calendar(2026)
df_calendar

req         WARNING 	DEFAULT CACHE ENABLED! (318.61 MB) C:\Users\mike5\AppData\Local\Temp\fastf1

,RoundNumber,Country,Location,EventDate,EventName,Session1,Session1DateUtc,Session2,Session2DateUtc,Session3,Session3DateUtc,Session4,Session4DateUtc,Session5,Session5DateUtc
0,0,Bahrain,Bahrain,2026-02-13,Pre-Season Testing,Practice 1,2026-02-11 08:00:00+01:00,Practice 2,2026-02-12 08:00:00+01:00,Practice 3,2026-02-13 08:00:00+01:00,None,NaT,None,NaT
1,0,Bahrain,Bahrain,2026-02-20,Pre-Season Testing,Practice 1,2026-02-18 08:00:00+01:00,Practice 2,2026-02-19 08:00:00+01:00,Practice 3,2026-02-20 08:00:00+01:00,None,NaT,None,NaT
2,1,Australia,Melbourne,2026-03-08,Australian Grand Prix,Practice 1,2026-03-06 02:30:00+01:00,Practice 2,2026-03-06 06:00:00+01:00,Practice 3,2026-03-07 02:30:00+01:00,Qualifying,2026-03-07 06:00:00+01:00,Race,2026-03-08 05:00:00+01:00
3,2,China,Shanghai,2026-03-15,Chinese Grand Prix,Practice 1,2026-03-13 04:30:00+01:00,Sprint Qualifying,2026-03-13 08:30:00+01:00,Sprint,2026-03-14 04:00:00+01:00,Qualifying,2026-03-14 08:00:00+01:00,Race,2026-03-15 08:00:00+01:00
4,3,Japan,Suzuka,2026-03-29,Japanese Grand Prix,Practice 1,2026-03-27 03:30:00+01:00,Practice 2,2026-03-27 07:00:00+01:00,Practice 3,2026-03-28 03:30:00+01:00,Qualifying,2026-03-28 07:00:00+01:00,Race,2026-03-29 07:00:00+02:00
5,4,Bahrain,Sakhir,2026-04-12,Bahrain Grand Prix,Practice 1,2026-04-10 13:30:00+02:00,Practice 2,2026-04-10 17:00:00+02:00,Practice 3,2026-04-11 14:30:00+02:00,Qualifying,2026-04-11 18:00:00+02:00,Race,2026-04-12 17:00:00+02:00
6,5,Saudi Arabia,Jeddah,2026-04-19,Saudi Arabian Grand Prix,Practice 1,2026-04-17 15:30:00+02:00,Practice 2,2026-04-17 19:00:00+02:00,Practice 3,2026-04-18 15:30:00+02:00,Qualifying,2026-04-18 19:00:00+02:00,Race,2026-04-19 19:00:00+02:00
7,6,United States,Miami Gardens,2026-05-03,Miami Grand Prix,Practice 1,2026-05-01 18:30:00+02:00,Sprint Qualifying,2026-05-01 22:30:00+02:00,Sprint,2026-05-02 18:00:00+02:00,Qualifying,2026-05-02 22:00:00+02:00,Race,2026-05-03 22:00:00+02:00
8,7,Canada,Montréal,2026-05-24,Canadian Grand Prix,Practice 1,2026-05-22 18:30:00+02:00,Sprint Qualifying,2026-05-22 22:30:00+02:00,Sprint,2026-05-23 18:00:00+02:00,Qualifying,2026-05-23 22:00:00+02:00,Race,2026-05-24 22:00:00+02:00
9,8,Monaco,Monte Carlo,2026-06-07,Monaco Grand Prix,Practice 1,2026-06-05 13:30:00+02:00,Practice 2,2026-06-05 17:00:00+02:00,Practice 3,2026-06-06 12:30:00+02:00,Qualifying,2026-06-06 16:00:00+02:00,Race,2026-06-07 15:00:00+02:00
10,9,Spain,Barcelona,2026-06-14,Barcelona Grand Prix,Practice 1,2026-06-12 13:30:00+02:00,Practice 2,2026-06-12 17:00:00+02:00,Practice 3,2026-06-13 12:30:00+02:00,Qualifying,2026-06-13 16:00:00+02:00,Race,2026-06-14 15:00:00+02:00
11,10,Austria,Spielberg,2026-06-28,Austrian Grand Prix,Practice 1,2026-06-26 13:30:00+02:00,Practice 2,2026-06-26 17:00:00+02:00,Practice 3,2026-06-27 12:30:00+02:00,Qualifying,2026-06-27 16:00:00+02:00,Race,2026-06-28 15:00:00+02:00
12,11,United Kingdom,Silverstone,2026-07-05,British Grand Prix,Practice 1,2026-07-03 13:30:00+02:00,Sprint Qualifying,2026-07-03 17:30:00+02:00,Sprint,2026-07-04 13:00:00+02:00,Qualifying,2026-07-04 17:00:00+02:00,Race,2026-07-05 16:00:00+02:00
13,12,Belgium,Spa-Francorchamps,2026-07-19,Belgian Grand Prix,Practice 1,2026-07-17 13:30:00+02:00,Practice 2,2026-07-17 17:00:00+02:00,Practice 3,2026-07-18 12:30:00+02:00,Qualifying,2026-07-18 16:00:00+02:00,Race,2026-07-19 15:00:00+02:00
14,13,Hungary,Budapest,2026-07-26,Hungarian Grand Prix,Practice 1,2026-07-24 13:30:00+02:00,Practice 2,2026-07-24 17:00:00+02:00,Practice 3,2026-07-25 12:30:00+02:00,Qualifying,2026-07-25 16:00:00+02:00,Race,2026-07-26 15:00:00+02:00
15,14,Netherlands,Zandvoort,2026-08-23,Dutch Grand Prix,Practice 1,2026-08-21 12:30:00+02:00,Sprint Qualifying,2026-08-21 16:30:00+02:00,Sprint,2026-08-22 12:00:00+02:00,Qualifying,2026-08-22 16:00:00+02:00,Race,2026-08-23 15:00:00+02:00
16,15,Italy,Monza,2026-09-06,Italian Grand Prix,Practice 1,2026-09-04 12:30:00+02:00,Practice 2,2026-09-04 16:00:00+02:00,Practice 3,2026-09-05 12:30:00+02:00,Qualifying,2026-09-05 16:00:00+02:00,Race,2026-09-06 15:00:00+02:00
17,16,Spain,Madrid,2026-09-13,Spanish Grand Prix,Practice 1,2026-09-11 13:30:00+02:00,Practice 2,2026-09-11 17:00:00+02:00,Practice 3,2026-09-12 12:30:00+02:00,Qualifying,2026-09-12 16:00:00+02:00,Race,2026-09-13 15:00:00+02:00
18,17,Azerbaijan,Baku,2026-09-26,Azerbaijan Grand Prix,Practice 1,2026-09-24 10:30:00+02:00,Practice 2,2026-09-24 14:00:00+02:00,Practice 3,2026-09-25 10:30:00+02:00,Qualifying,2026-09-25 14:00:00+02:00,Race,2026-09-26 13:00:00+02:00
19,18,Singapore,Marina Bay,2026-10-11,Singapore Grand Prix,Practice 1,2026-10-09 10:30:00+02:00,Sprint Qualifying,2026-10-09 14:30:00+02:00,Sprint,2026-10-10 11:00:00+02:00,Qualifying,2026-10-10 15:00:00+02:00,Race,2026-10-11 14:00:00+02:00
20,19,United States,Austin,2026-10-25,United States Grand Prix,Practice 1,2026-10-23 19:30:00+02:00,Practice 2,2026-10-23 23:00:00+02:00,Practice 3,2026-10-24 19:30:00+02:00,Qualifying,2026-10-24 23:00:00+02:00,Race,2026-10-25 21:00:00+01:00
21,20,Mexico,Mexico City,2026-11-01,Mexico City Grand Prix,Practice 1,2026-10-30 19:30:00+01:00,Practice 2,2026-10-30 23:00:00+01:00,Practice 3,2026-10-31 18:30:00+01:00,Qualifying,2026-10-31 22:00:00+01:00,Race,2026-11-01 21:00:00+01:00
22,21,Brazil,São Paulo,2026-11-08,São Paulo Grand Prix,Practice 1,2026-11-06 16:30:00+01:00,Practice 2,2026-11-06 20:00:00+01:00,Practice 3,2026-11-07 15:30:00+01:00,Qualifying,2026-11-07 19:00:00+01:00,Race,2026-11-08 18:00:00+01:00
23,22,United States,Las Vegas,2026-11-21,Las Vegas Grand Prix,Practice 1,2026-11-20 01:30:00+01:00,Practice 2,2026-11-20 05:00:00+01:00,Practice 3,2026-11-21 01:30:00+01:00,Qualifying,2026-11-21 05:00:00+01:00,Race,2026-11-22 05:00:00+01:00
24,23,Qatar,Lusail,2026-11-29,Qatar Grand Prix,Practice 1,2026-11-27 14:30:00+01:00,Practice 2,2026-11-27 18:00:00+01:00,Practice 3,2026-11-28 15:30:00+01:00,Qualifying,2026-11-28 19:00:00+01:00,Race,2026-11-29 17:00:00+01:00
25,24,United Arab Emirates,Yas Marina,2026-12-06,Abu Dhabi Grand Prix,Practice 1,2026-12-04 10:30:00+01:00,Practice 2,2026-12-04 14:00:00+01:00,Practice 3,2026-12-05 11:30:00+01:00,Qualifying,2026-12-05 15:00:00+01:00,Race,2026-12-06 14:00:00+01:00

In [9]:
s_sess = fastf1.get_session(2026, 9, 'Q')
s_sess.load(laps=True, telemetry=True, weather=True, messages=False)

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
core        WARNING 	Cannot calculate qualifying results: missing information about deleted laps. Make sure that race control messages are being loaded.
logger      WARNING 	Failed to calculate quali results from lap times!
core           INFO 	Finished loading data for 22 drivers: ['44', '12', '16', '63', '81', '3', '1', '6', '27', '30', '43', '5', '41', '87', '55', '31', '23', '77', '11', '14', '10', '18']

In [10]:
s_sess.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
44,44,L HAMILTON,HAM,,Ferrari,ED1131,,Lewis,Hamilton,Lewis Hamilton,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,,Mercedes,00D7B6,,Kimi,Antonelli,Kimi Antonelli,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
16,16,C LECLERC,LEC,,Ferrari,ED1131,,Charles,Leclerc,Charles Leclerc,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,,Mercedes,00D7B6,,George,Russell,George Russell,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,,McLaren,F47600,,Oscar,Piastri,Oscar Piastri,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,,Red Bull Racing,4781D7,,Max,Verstappen,Max Verstappen,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
1,1,L NORRIS,NOR,,McLaren,F47600,,Lando,Norris,Lando Norris,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
6,6,I HADJAR,HAD,,Red Bull Racing,4781D7,,Isack,Hadjar,Isack Hadjar,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,,Audi,F50537,,Nico,Hulkenberg,Nico Hulkenberg,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,,Racing Bulls,6C98FF,,Liam,Lawson,Liam Lawson,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,,Alpine,00A1E8,,Franco,Colapinto,Franco Colapinto,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,,Audi,F50537,,Gabriel,Bortoleto,Gabriel Bortoleto,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,,Racing Bulls,6C98FF,,Arvid,Lindblad,Arvid Lindblad,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,,Haas F1 Team,9C9FA2,,Oliver,Bearman,Oliver Bearman,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,,Williams,1868DB,,Carlos,Sainz,Carlos Sainz,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,,Haas F1 Team,9C9FA2,,Esteban,Ocon,Esteban Ocon,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,,Williams,1868DB,,Alexander,Albon,Alexander Albon,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,,Cadillac,909090,,Valtteri,Bottas,Valtteri Bottas,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,,Cadillac,909090,,Sergio,Perez,Sergio Perez,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,,Alpine,00A1E8,,Pierre,Gasly,Pierre Gasly,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN

In [12]:
s_sess.drivers

['63',
 '12',
 '16',
 '44',
 '1',
 '3',
 '87',
 '41',
 '5',
 '10',
 '31',
 '23',
 '30',
 '43',
 '55',
 '11',
 '18',
 '14',
 '77',
 '6',
 '81',
 '27']

In [28]:
s_sess.laps.pick_driver('PIA')

c:\Users\mike5\anaconda3\Lib\site-packages\fastf1\core.py:3129: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.
  warnings.warn(("pick_driver is deprecated and will be removed"

Empty DataFrame
Columns: [Time, Driver, DriverNumber, LapTime, LapNumber, Stint, PitOutTime, PitInTime, Sector1Time, Sector2Time, Sector3Time, Sector1SessionTime, Sector2SessionTime, Sector3SessionTime, SpeedI1, SpeedI2, SpeedFL, SpeedST, IsPersonalBest, Compound, TyreLife, FreshTyre, Team, LapStartTime, LapStartDate, TrackStatus, Position, Deleted, DeletedReason, FastF1Generated, IsAccurate]
Index: []

[0 rows x 31 columns]

In [27]:
s_sess.get_driver('PIA')

DriverNumber                                                         81
BroadcastName                                                 O PIASTRI
Abbreviation                                                        PIA
DriverId                                                        piastri
TeamName                                                        McLaren
TeamColor                                                        F47600
TeamId                                                          mclaren
FirstName                                                         Oscar
LastName                                                        Piastri
FullName                                                  Oscar Piastri
HeadshotUrl           https://media.formula1.com/d_driver_fallback_i...
CountryCode
Position                                                           21.0
ClassifiedPosition                                                    W
GridPosition                                                        5.0
Q1                                                                  NaT
Q2                                                                  NaT
Q3                                                                  NaT
Time                                                                NaT
Status                                                    Did not start
Points                                                              0.0
Laps                                                                0.0
Name: 81, dtype: object

In [10]:
s_sess.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:18:17.451000,RUS,63,0 days 00:01:51.876000,1.0,1.0,0 days 00:16:28.955000,NaT,0 days 00:00:41.997000,0 days 00:00:19.351000,...,True,Mercedes,0 days 00:16:28.955000,NaT,1,NaN,None,,False,False
1,0 days 00:19:37.291000,RUS,63,0 days 00:01:19.840000,2.0,1.0,NaT,NaT,0 days 00:00:27.990000,0 days 00:00:17.599000,...,True,Mercedes,0 days 00:18:17.451000,NaT,1,NaN,None,,False,True
2,0 days 00:21:38.860000,RUS,63,0 days 00:02:01.569000,3.0,1.0,NaT,0 days 00:21:24.695000,0 days 00:00:40.873000,0 days 00:00:22.025000,...,True,Mercedes,0 days 00:19:37.291000,NaT,1,NaN,None,,False,False
3,0 days 00:32:02.050000,RUS,63,NaT,4.0,2.0,0 days 00:21:42.023000,0 days 00:23:38.517000,0 days 00:00:46.779000,0 days 00:00:22.489000,...,False,Mercedes,0 days 00:21:38.860000,NaT,125,NaN,None,,False,False
4,0 days 00:33:52.363000,RUS,63,0 days 00:01:50.313000,5.0,3.0,0 days 00:32:12.182000,NaT,0 days 00:00:52.390000,0 days 00:00:19.564000,...,False,Mercedes,0 days 00:32:12.182000,NaT,1,NaN,None,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,0 days 00:37:40.830000,BOT,77,0 days 00:01:44.306000,6.0,3.0,0 days 00:35:58.814000,NaT,0 days 00:00:41.112000,0 days 00:00:20.231000,...,True,Cadillac,0 days 00:35:58.814000,NaT,1,NaN,None,,False,False
349,0 days 00:39:04.074000,BOT,77,0 days 00:01:23.244000,7.0,3.0,NaT,NaT,0 days 00:00:29.198000,0 days 00:00:18.068000,...,True,Cadillac,0 days 00:37:40.830000,NaT,1,NaN,None,,False,True
350,0 days 00:40:53.451000,BOT,77,NaT,8.0,3.0,NaT,0 days 00:40:53.451000,0 days 00:00:37.594000,0 days 00:00:24.343000,...,True,Cadillac,0 days 00:39:04.074000,NaT,1,NaN,None,,False,False
351,0 days 00:22:51.416000,VER,3,0 days 00:01:42.025000,1.0,1.0,0 days 00:21:13.117000,NaT,0 days 00:00:41.429000,0 days 00:00:19.065000,...,True,Red Bull Racing,0 days 00:21:13.117000,NaT,1,NaN,None,,False,False
352,0 days 00:27:57.674000,VER,3,NaT,2.0,1.0,NaT,0 days 00:27:57.674000,0 days 00:00:41.429000,NaT,...,True,Red Bull Racing,0 days 00:22:51.416000,NaT,125,NaN,None,,False,False

In [9]:
s_sess.laps['Driver'].unique().tolist()

['RUS',
 'ANT',
 'HAD',
 'LEC',
 'PIA',
 'NOR',
 'HAM',
 'LAW',
 'LIN',
 'BOR',
 'HUL',
 'BEA',
 'OCO',
 'GAS',
 'ALB',
 'COL',
 'ALO',
 'PER',
 'BOT',
 'VER']